### ISSUE TITLE
"AttributeError: module 'Partitioner' has no attribute 'Partitioner'

### ISSUE THREAD

**Issue by alocate** [ardaegeunlu/X-armed-Bandits#1]
Hi, tried to run your code, but it seems like Partitioner.py is exactly the same as HOO.py. Is this intended?

**Comment by ardaegeunlu** [comment]
Hi,

Thanks for pointing it out. It was definitely not intended and it should be fixed now.

**Comment by ardaegeunlu** [comment]
If you have any other persisting issues, or further questions please do not hesitate to ask.
